name: Build and Release APK for LSPosed

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK (LSPosed compatible APK)
        run: ./gradlew assembleRelease --stacktrace

      - name: Check APK exists before upload
        run: |
          if [ ! -f app/build/outputs/apk/release/app-release.apk ]; then
            echo "APK not found! Failing build."
            exit 1
          fi

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
